url-historical: "https://historical-forecast-api.open-meteo.com/v1/forecast"
url-forecast: "https://api.open-meteo.com/v1/forecast"
hourly:
  - temperature_2m
  - relative_humidity_2m
  - dew_point_2m
  - apparent_temperature
  - precipitation_probability
  - precipitation
  - rain
  - snowfall
  - surface_pressure
  - evapotranspiration
  - wind_speed_10m
  - wind_direction_10m