codes:
  - 104
  - 917
  - 503
  - 515
  - 715
  - 636
  - 111
  - 365
  - 902
  - 149
  - 232

"104":
  yearly:
    - winter
    - fall
  monthly: None
  weekly: None
  daily:
    - 2-10
    - 10-14
    - 14-24

"917":
  yearly:
    - winter
    - fall
  monthly: None
  weekly: None
  daily:
    - 3-10
    - 10-24

"503":
  yearly:
    - winter
  monthly: None
  weekly: None
  daily:
    - 2-10
    - 10-12
    - 12-24

"515":
  yearly:
    - winter
    - fall
  monthly: None
  weekly:
    - friday
    - saturday
  daily:
    - 2-10
    - 10-12
    - 12-24

"715":
  yearly:
    - winter
    - fall
  monthly: None
  weekly: None
  daily:
    - 2-10
    - 10-12
    - 12-24

"636":
  yearly: None
  monthly: None
  weekly: None
  daily: None

"111":
  yearly:
    - winter
    - fall
  monthly: None
  weekly: None
  daily:
    - 2-10
    - 10-12
    - 12-24

"365":
  yearly:
    - spring
    - summer
    - fall
    - winter
  monthly: None
  weekly: None
  daily:
    - 5-9
    - 9-12
    - 12-20
    - 20-24

"902":
  yearly:
    - winter
    - fall
  monthly: None
  weekly: None
  daily:
    - 3-10
    - 10-12
    - 12-24

"149":
  yearly:
    - winter
    - fall
  monthly: None
  weekly: None
  daily:
    - 3-10
    - 10-12
    - 12-24

"232":
  yearly:
    - winter
    - fall
  monthly: None
  weekly: None
  daily:
    - 3-10
    - 10-12
    - 12-24

