bar:
  date: text
  hour: int
  load_level: varchar(10)

plant_data:
  id: varchar(50)
  name: varchar(100)
  type: varchar(10)
  utm: text

plant_temp:
  id: varchar(50)
  name: varchar(100)
  date: text
  hour: int
  scadaf: float
  temp_sens: float

energy:
  id: varchar(50)
  code: varchar(50)
  name: varchar(50)
  date: text
  hour: int
  generation: float

selleroffer:
  id: varchar(50)
  name: varchar(100)
  code: varchar(50)
  date: text
  hour: int
  declared: float

factors:
  id: varchar(50)
  name: varchar(100)
  code: varchar(50)
  date: text
  a: float
  b: float

status:
  id: varchar(50)
  code: varchar(50)
  date: text
  hour: int
  status: varchar(10)

load:
  date: text
  hour: int
  forecasted_load: float

commitment:
  id: varchar(10)
  name: varchar(100)
  code: varchar(10)
  date: text
  hour: int
  required: float

weather:
  id: varchar(50)
  date: text
  hour: int
  temperature: float
  humidity: float
  dew: float
  apparent_temperature: float
  precipitation: float
  rain: float
  snow: float
  surface_pressure: float
  evapotranspiration: float
  wind_speed: float
  wind_direction: float

declaration_check:
  id: varchar(50)
  name: varchar(50)
  code: varchar(50)
  date: text
  hour: int
  a: float
  b: float
  temperature: float
  declared: float
  calculated: float